### ISSUE TITLE
Support HEIC Photos?

### ISSUE THREAD

**Issue by RecepCil** [photo-cli/photo-cli#17]
Is it possible to use your photo-cli tool for HEIC format photos from an Apple device? I've tried like below but I got the following output. Thanks in advance.

**Command:**
`photo-cli copy -o ordered-photos -s DateTimeWithMinutes -f FlattenAllSubFolders -n PaddingZeroCharacter`

**Output:**
Searching photos: finished. 0 photos found.
No photo found on folder: /Users/cilrecep/photos
Process failed with a error code 21 (NoPhotoFoundOnDirectory)

**Comment by alpcoker** [comment]
Hello @RecepCil ,

Thanks for your interest & reporting that issue. 

Sorry for that currently the photo collector service only searches for JPG files, so it couldn't find any photos in your folder.  

If the internal library, [Metadata-Extractor](https://github.com/drewnoakes/metadata-extractor-dotnet) that I am using to get Exif Data is working with HEIC files. I will add this format too. Once I add it, I will notify this issue too.

**Comment by RecepCil** [comment]
Would it be okay to add JPEG support as well?

**Comment by alpcoker** [comment]
Yes, good catch. Thanks @RecepCil, please add. It would be nice. I forgot to add it because all my devices is producing only jpg files.
